# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


House.create(name: "Gryffindor", description: "Gryffindor values bravery, daring, nerve, and chivalry. Its emblematic animal is the lion and its colours are scarlet and gold. Minerva McGonagall was the most recent Head of Gryffindor. Sir Nicholas de Mimsy-Porpington, also known as 'Nearly Headless Nick', was the house ghost. The founder of the house was Godric Gryffindor. Gryffindor corresponds to the element of Fire. The common room was located in one of the highest towers at Hogwarts, the entrance was situated on the seventh floor in the east wing of the castle and is guarded by a portrait of The Fat Lady. She permits entrance if given the correct password, which is changed numerous times throughout the school year. Famous Gryffindors include Albus Dumbledore, Harry Potter, and Celestina Warbeck.")
House.create(name: "Hufflepuff", description: "Hufflepuff values hard work, dedication, patience, loyalty, and fair play. Its emblematic animal is the badger, and Yellow and Black are its colours. Pomona Sprout was the Head of Hufflepuff during 1991-1998, Sprout left the post of Head of Hufflepuff and Herbology Professor sometime before 2017 and her successor for the position of Head of Hufflepuff is currently unknown. The Fat Friar is its ghost. The founder of the house was Helga Hufflepuff. Hufflepuff corresponds to the element of earth. The Hufflepuff dormitories and common room are located somewhere in the basement, near the castle's kitchens. It can be accessed by tapping the barrel two from the bottom, middle of the second row in the rhythm of 'Helga Hufflepuff' and is described as being a cosy and welcoming place with yellow hangings, fat armchairs, and underground tunnels that lead to the dormitories, which have perfectly round doors, similar to barrel tops. Famous Hufflepuffs include Hengist of Woodcroft (founder of Hogsmeade), Newt Scamander, and Artemisia Lufkin (first female minister for magic).")
House.create(name: "Ravenclaw", description: "Ravenclaw values intelligence, knowledge, and wit. Its emblematic animal is the eagle, and its colours are blue and bronze. The Ravenclaw Head of House in the 1990s was Filius Flitwick. The ghost of Ravenclaw is the Grey Lady, who was the daughter of Rowena Ravenclaw, the house's founder. Ravenclaw corresponds to the element of air. The Ravenclaw common room and dormitories are located in a tower on the west side of the castle. Ravenclaw students must answer a riddle as opposed to giving a password to enter their dormitories. This riddle, however, can be answered by non-Ravenclaws. Famous Ravenclaws include Gilderoy Lockheart, Ignatia Wildsmith (inventor of Floo powder), and Garrick Ollivander.")
House.create(name: "Slytherin", description: "Slytherin house values ambition, cunning and resourcefulness and was founded by Salazar Slytherin. Its emblematic animal is the serpent, and its colours are emerald green and silver. Professor Horace Slughorn was the Head of Slytherin during the 1997–1998 school year, replacing Severus Snape, who as well, replaced Slughorn as Potions Professor when he retired for the first time several years prior. The Bloody Baron is the house ghost. The founder of the house was Salazar Slytherin. Slytherin corresponds roughly to the element of water. The Slytherin dormitories and common room are reached through a bare stone wall in the Dungeons. The Slytherin common room lies beneath the Black Lake. It is a long, low underground room with rough stone walls and silver lamps hanging from the ceiling. Famous Slytherins include Merlin, Tom Riddle, and Dolores Umbridge.")

Professor.create(name: "Aurora Sinistra", bio: "Professor Sinistra teaches Astromomy at Hogwarts.", house_id: )
Professor.create(name: "Filius Flitwick", bio: "Professor Filius Flitwick (b. 17 October[1] 1958 or earlier[3]) was a part-goblin, part-wizard[10] who attended Hogwarts School of Witchcraft and Wizardry and was sorted into Ravenclaw House,[11] being an intelligent young man and a model student.[12] Some time after his graduation, Flitwick returned to Hogwarts and became the Charms Master, as well as the Head of Ravenclaw House.[7]
During the First and Second Wizarding Wars, Flitwick opposed Lord Voldemort. In 1995, he also opposed Dolores Umbridge, the High Inquisitor of Hogwarts, and, in 1997, fought at the Battle of the Astronomy Tower, after which he attended the Funeral of Albus Dumbledore. He also protected the students from the Carrows in the 1997-1998 school year. On 2 May 1998, he partook in the Battle of Hogwarts and defeated many Death Eaters.
He survived the war, and likely continued to teach Charms at Hogwarts to future generations of students.", house_id: )
Professor.create(name: "Remus Lupin", bio:, house_id: )
Professor.create(name: "Rolanda Hooch", bio:, house_id: )
Professor.create(name: "Pomona Sprout", bio:, house_id: )
Professor.create(name: "Cuthbert Binns", bio:, house_id: )
Professor.create(name: "Severus Snape", bio:, house_id: )
Professor.create(name: "Minerva McGonagall", bio:, house_id: )
Professor.create(name: "Septima Vector", bio:, house_id: )
Professor.create(name: "Rubeus Hagrid", bio:, house_id: )
Professor.create(name: "Sybill Trelawney", bio: "", house_id: )
Professor.create(name: "Charity Burbage", bio:, house_id: )
Professor.create(name: "Bathsheda Babbling", bio:, house_id: )
Professor.create(name: "Wilkie Twycross", bio:, house_id: )


Lesson.create(name: "Astronomy", description: "Astronomy is the only field of study at Hogwarts that has a direct equivalent in the Muggle world. Astronomy classes take place in the Astronomy Tower, the tallest tower in Hogwarts, and are taught by Professor Aurora Sinistra. Lessons involve observations of the night skies with telescopes. Lessons are held every week at midnight, and first years have lessons on Wednesday. Known student homework activities include learning the names of stars, constellations and planets, and their location, movements, and environments.")
Lesson.create(name: "Charms", description: "Charms is the type of spells concerned with giving an object new and unexpected properties, and hence this class mainly consists on learning those sorts of spells. Charms classes are described as notoriously noisy and chaotic, as the lessons are largely practical. Many of the exposition sequences in the books are set in Charms classes, which are on the second floor of Hogwarts.")
Lesson.create(name: "Defence Against the Dark Arts", description: "Defence Against the Dark Arts (sometimes written as DADA) is a subject taught at Hogwarts School of Witchcraft and Wizardry and Ilvermorny School of Witchcraft and Wizardry[1]. In this class students learn how to magically defend themselves against Dark Creatures, the Dark Arts, and other dark charms. Offensive magic is also taught in this class, such as how to duel, which requires the use of both offensive and defensive magic. The subject is the core class at Hogwarts. The position of Defence Against the Dark Arts professor here was once rumoured to be jinxed, as no teacher could hold the post for more than a year. Tom Marvolo Riddle jinxed the position because Dumbledore did not give him the job when he applied for it.[3] The fact that no teacher has lasted longer than a year meant that the subject has had numerous Professors. Ilvermorny began teaching the subject in the 17th century. Also Harry Potter would occasionally deliver Defence Against the Dark Arts lectures at Hogwarts.")
Lesson.create(name: "Flying", description: "Flying is the class that teaches the use of broomsticks made for the use of flying and is taught only to Hogwarts first years by Rolanda Hooch. The subject is the only one that requires physicality.")
Lesson.create(name: "Herobology", description: "Herbology is the study of magical plants and how to take care of, utilise and combat them. There are at least three greenhouses, holding a variety of magical plants of varying degrees of lethality. Herbology is also the subject Neville Longbottom excels in. He later replaces Professor Sprout as the Herbology teacher.")
Lesson.create(name: "History of Magic", description: "History of Magic is the study of magical history. Cuthbert Binns' lessons are depicted as some of the most boring at Hogwarts. They are only lectures, given without pause, about significant events in wizarding history. Topics have included Goblin Rebellions, Giant wars, and the origins of wizarding secrecy. This is the only class at Hogwarts that is taught by a ghost, as the professor never noticed he had died and simply continued teaching as if nothing had changed."
Lesson.create(name: "Potions", description: "Potions is described as the art of creating mixtures with magical effects. It requires the correct mixing and stirring of ingredients at the right times and temperatures. Snape's lessons are depicted as unhappy, oppressing times set in a gloomy dungeon in the basement of the castle, whilst Horace Slughorn's, who replaces Severus Snape as Potions Master, is shown as more cheerful and even fun at times.")
Lesson.create(name: "Transfiguration", description: "Transfiguration is the art of changing the form or appearance of an object, and hence this is what this class teaches. Transfiguration is a theory-based subject, including topics such as 'Switching Spells' (altering only a part of some object, such as giving a human rabbit's ears); Vanishing Spells (causing an object to completely disappear); and Conjuring Spells (creating objects out of thin air). It is possible to change inanimate objects into animate ones and vice versa — Minerva McGonagall, the class's teacher, transfigures her desk into a pig.")
Lesson.create(name: "Arithmancy", description: "Arithmancy is a branch of magic concerned with the magical properties of numbers. It is a favourite subject of Hermione Granger. Arithmancy is reportedly difficult, as it requires memorising or working with many charts. It is also an elective course, that can be taken by students third year and above. The subject is taught by Professor Septima Vector. It is separated into normal Arithmancy and Advanced Arithmancy Studies", professor_id: , )
Lesson.create(name: "Care of Magical Creatures", description: "Care of Magical Creatures is the class which instructs students on how to care for magical beasts. Classes are held outside the castle. In Harry's first two years, the class is taken by Professor Silvanus Kettleburn who then retires 'in order to enjoy more time with his remaining limbs'. Dumbledore then recruits the gamekeeper Rubeus Hagrid to accept a teaching position along with his gamekeeping duties. Although Hagrid is obviously very experienced and knowledgeable, he consistently misjudges the risk that the animals he uses in his lessons pose to his students, which sometimes results in chaos. When Hagrid is absent, his lessons are taken over by Professor Grubbly-Plank, a witch and acquaintance of Dumbledore's.", professor_id: , )
Lesson.create(name: "Divination", description: "Divination is the art of predicting the future. Various methods are described, including tea leaves, Fire-omens, Crystal balls, Palmistry, Cartomancy (including the reading of conventional playing cards and the tarot), astrology, and Dream interpretations. Divination is described by Professor McGonagall as 'one of the most imprecise branches of magic'. Supporters of the subject claim that it is an inexact science that requires innate gifts like the 'Inner Eye'. Those opposed claim that the subject is irrelevant and fraudulent. Harry is first taught Divination by Professor Trelawney, and then later by Firenze after Trelawney is sacked by Dolores Umbridge in Harry's fifth year. In the sixth (and presumably seventh) year, Firenze and Professor Trelawney teach Divination.", professor_id: , )
Lesson.create(name: "Muggle Studies", description: "Muggle Studies is a class taught by Charity Burbage which involves the study of the Muggle (non-magical) culture 'from a wizarding point of view.' It also includes Muggle Art and Muggle Music. The only need for witches and wizards to learn about Muggle ways and means is to ensure they can blend in with Muggles while needing to do so (for example, at the 1994 Quidditch World Cup). As the class is only mentioned as being taken by Hermione, and for just one year, little is known about its curriculum.", professor_id: , )
Lesson.create(name: "Ancient Runes", description: "The Study of Ancient Runes is a general theoretical subject that studies ancient runic scripts. It is taught by Professor Bathsheda Babbling. It is an elective course, that can be taken by students third year and above.", professor_id: , )
Lesson.create(name: "Apparition", description: "Apparition is the magical form of teleportation in the wizarding world. Lessons are optional to those in the sixth and seventh years. In the wizarding world, performing Apparition requires a licence and may only be legally performed by people over seventeen years of age. The described reason for the restriction is that Apparition is dangerous if done improperly: insufficient concentration may lead to body parts being left behind in an unfortunate side-effect known as splinching. Although, as Hermione points out innumerable times throughout the series, magical enchantments on Hogwarts Castle and grounds prevent Apparition and Disapparition inside the castle, these protections are temporarily relaxed within the Great Hall for short periods to permit students to practise Apparition. Wilkie Twycross, a Ministry of Magic Apparition Instructor, offers lessons in Apparition to sixth-years.", professor_id: , )
